### ISSUE TITLE
Copy to clipboard not working

### ISSUE THREAD

**Issue by samtere** [robbalian/pinkarrows#41]
On both Firefox and Chrome on Windows 10, the button doesn't work consistently. On most occasions you press it and it turns blue for 3-4 seconds but nothing is copied to the clipboard.

**Comment by robbalian** [comment]
thanks for reporting, I'll check it out

**Comment by robbalian** [comment]
Should be fixed. Thanks for testing on multiple browsers. Please try again when you have the chance @samtere

**Comment by samtere** [comment]
It's resolved. Thanks!
